name: cartalogue
description: Car Manufacturers Catalogue.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^10.1.0
  flutter_riverpod: ^2.3.7
  shared_preferences: ^2.2.0
  equatable: ^2.0.5
  connectivity_plus: ^4.0.2
  dio: ^5.3.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  http_mock_adapter: ^0.4.4
  flutter_lints: ^2.0.0
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/

  